// expose full MTR station dictionary & name→code map
window.MTR_STATIONS = {
  AEL:{name:'Airport Express Line',type:'line'},
  TCL:{name:'Tung Chung Line',type:'line'},
  TML:{name:'Tuen Ma Line',type:'line'},
  TKL:{name:'Tseung Kwan O Line',type:'line'},
  EAL:{name:'East Rail Line',type:'line'},
  SIL:{name:'South Island Line',type:'line'},
  TWL:{name:'Tsuen Wan Line',type:'line'},
  ISL:{name:'Island Line',type:'line'},
  KTL:{name:'Kwun Tong Line',type:'line'},
  DRL:{name:'Disneyland Resort Line',type:'line'},
  AIR:{name:'Airport',lines:['AEL']},
  AWE:{name:'AsiaWorld Expo',lines:['AEL']},
  HOK:{name:'Hong Kong',lines:['AEL','TCL']},
  KOW:{name:'Kowloon',lines:['AEL','TCL']},
  TSY:{name:'Tsing Yi',lines:['AEL','TCL']},
  OLY:{name:'Olympic',lines:['TCL']},
  NAC:{name:'Nam Cheong',lines:['TCL','TML']},
  LAK:{name:'Lai King',lines:['TCL','TWL']},
  TUC:{name:'Tung Chung',lines:['TCL']},
  SUN:{name:'Sunny Bay',lines:['TCL','DRL']},
  WKS:{name:'Wu Kai Sha',lines:['TML']},
  MOS:{name:'Ma On Shan',lines:['TML']},
  HEO:{name:'Heng On',lines:['TML']},
  TSH:{name:'Tai Shui Hang',lines:['TML']},
  SHM:{name:'Shek Mun',lines:['TML']},
  CIO:{name:'City One',lines:['TML']},
  STW:{name:'Sha Tin Wai',lines:['TML']},
  CKT:{name:'Che Kung Temple',lines:['TML']},
  TAW:{name:'Tai Wai',lines:['TML','EAL']},
  HIK:{name:'Hin Keng',lines:['TML']},
  DIH:{name:'Diamond Hill',lines:['TML','KTL']},
  KAT:{name:'Kai Tak',lines:['TML']},
  SUW:{name:'Sung Wong Toi',lines:['TML']},
  TKW:{name:'To Kwa Wan',lines:['TML']},
  HOM:{name:'Ho Man Tin',lines:['TML','KTL']},
  HUH:{name:'Hung Hom',lines:['TML','EAL']},
  ETS:{name:'East Tsim Sha Tsui',lines:['TML']},
  AUS:{name:'Austin',lines:['TML']},
  MEF:{name:'Mei Foo',lines:['TML','TWL']},
  TWW:{name:'Tsuen Wan West',lines:['TML']},
  KSR:{name:'Kam Sheung Road',lines:['TML']},
  YUL:{name:'Yuen Long',lines:['TML']},
  LOP:{name:'Long Ping',lines:['TML']},
  TIS:{name:'Tin Shui Wai',lines:['TML']},
  SIH:{name:'Siu Hong',lines:['TML']},
  TUM:{name:'Tuen Mun',lines:['TML']},
  NOP:{name:'North Point',lines:['TKL','ISL']},
  QUB:{name:'Quarry Bay',lines:['TKL','ISL']},
  YAT:{name:'Yau Tong',lines:['TKL','KTL']},
  TIK:{name:'Tiu Keng Leng',lines:['TKL','KTL']},
  TKO:{name:'Tseung Kwan O',lines:['TKL']},
  LHP:{name:'LOHAS Park',lines:['TKL']},
  HAH:{name:'Hang Hau',lines:['TKL']},
  POA:{name:'Po Lam',lines:['TKL']},
  ADM:{name:'Admiralty',lines:['EAL','SIL','TWL','ISL']},
  EXC:{name:'Exhibition Centre',lines:['EAL']},
  MKK:{name:'Mong Kok East',lines:['EAL']},
  KOT:{name:'Kowloon Tong',lines:['EAL','KTL']},
  SHT:{name:'Sha Tin',lines:['EAL']},
  FOT:{name:'Fo Tan',lines:['EAL']},
  RAC:{name:'Racecourse',lines:['EAL']},
  UNI:{name:'University',lines:['EAL']},
  TAP:{name:'Tai Po Market',lines:['EAL']},
  TWO:{name:'Tai Wo',lines:['EAL']},
  FAN:{name:'Fanling',lines:['EAL']},
  SHS:{name:'Sheung Shui',lines:['EAL']},
  LOW:{name:'Lo Wu',lines:['EAL']},
  LMC:{name:'Lok Ma Chau',lines:['EAL']},
  OCP:{name:'Ocean Park',lines:['SIL']},
  WCH:{name:'Wong Chuk Hang',lines:['SIL']},
  LET:{name:'Lei Tung',lines:['SIL']},
  SOH:{name:'South Horizons',lines:['SIL']},
  CEN:{name:'Central',lines:['TWL','ISL']},
  TST:{name:'Tsim Sha Tsui',lines:['TWL']},
  JOR:{name:'Jordan',lines:['TWL']},
  YMT:{name:'Yau Ma Tei',lines:['TWL','KTL']},
  MOK:{name:'Mong Kok',lines:['TWL','KTL']},
  PRE:{name:'Prince Edward',lines:['TWL','KTL']},
  SSP:{name:'Sham Shui Po',lines:['TWL']},
  CSW:{name:'Cheung Sha Wan',lines:['TWL']},
  LCK:{name:'Lai Chi Kok',lines:['TWL']},
  KWF:{name:'Kwai Fong',lines:['TWL']},
  KWH:{name:'Kwai Hing',lines:['TWL']},
  TWH:{name:'Tai Wo Hau',lines:['TWL']},
  TSW:{name:'Tsuen Wan',lines:['TWL']},
  WHA:{name:'Whampoa',lines:['KTL']},
  SKM:{name:'Shek Kip Mei',lines:['KTL']},
  LOF:{name:'Lok Fu',lines:['KTL']},
  WTS:{name:'Wong Tai Sin',lines:['KTL']},
  CHH:{name:'Choi Hung',lines:['KTL']},
  KOB:{name:'Kowloon Bay',lines:['KTL']},
  NTK:{name:'Ngau Tau Kok',lines:['KTL']},
  KWT:{name:'Kwun Tong',lines:['KTL']},
  LAT:{name:'Lam Tin',lines:['KTL']},
  KET:{name:'Kennedy Town',lines:['ISL']},
  HKU:{name:'HKU',lines:['ISL']},
  SYP:{name:'Sai Ying Pun',lines:['ISL']},
  SHW:{name:'Sheung Wan',lines:['ISL']},
  WAC:{name:'Wan Chai',lines:['ISL']},
  CAB:{name:'Causeway Bay',lines:['ISL']},
  TIH:{name:'Tin Hau',lines:['ISL']},
  FOH:{name:'Fortress Hill',lines:['ISL']},
  TAK:{name:'Tai Koo',lines:['ISL']},
  SWH:{name:'Sai Wan Ho',lines:['ISL']},
  SKW:{name:'Shau Kei Wan',lines:['ISL']},
  HFC:{name:'Heng Fa Chuen',lines:['ISL']},
  CHW:{name:'Chai Wan',lines:['ISL']},
  DIS:{name:'Disneyland Resort',lines:['DRL']}
};
window.MTR_NAME_TO_CODE = Object.entries(window.MTR_STATIONS)
  .reduce((m,[c,i]) => {
    if (i.lines) m[i.name.toLowerCase()] = c;
    return m;
  }, {});